from typing import TypedDict, Optional, Dict, Any, List
from langgraph.graph import StateGraph, END
import sys
import os

# Ensure the app can find the agents
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from Agent_1.inflation_outlook_agent import MacroAgent
from Agent_2.corporate_analysis_agent import CompanyDataAgent
from Agent_3.scenario_resilience_agent import FinancialAgent
from Executive_intelligence_agent import ReportAgent

# Initialize agents once to keep models in memory
print("⚙️ Initializing Agents for LangGraph Pipeline...")
macro_agent = MacroAgent()
company_agent = CompanyDataAgent()
financial_agent = FinancialAgent()
report_agent = ReportAgent()

# ==========================================================
# 1. Define the State
# This is the "memory" that gets passed from agent to agent
# ==========================================================
class AgentState(TypedDict):
    company_name: str
    months_ahead: int
    
    # Outputs from Agent 1 (Macro)
    macro_results: Optional[Dict[str, Any]]
    proj_inf: Optional[float]
    proj_repo: Optional[float]
    proj_oil: Optional[float]
    
    # Outputs from Agent 2 (Company Baseline & Financial Statements)
    historical_financials: Optional[Dict[str, Any]]
    
    # Outputs from Agent 3 (Financial Forecasts)
    financial_forecasts: Optional[Dict[str, Any]]
    macro_impacts: Optional[Dict[str, Any]]
    
    # Outputs from Agent 4 (LLM Report)
    investment_report: Optional[str]
    
    # Error handling
    error: Optional[str]

# ==========================================================
# 2. Define the Nodes (The Agents)
# ==========================================================
def run_macro_node(state: AgentState):
    """Node 1: Runs Agent 1 to forecast the macro economy."""
    print(f"--> [Node 1] Running Inflation Outlook Agent for {state['months_ahead']} months ahead...")
    try:
        macro_result = macro_agent.execute(
            input_payload=None, # None forces it to fetch the latest from CSV
            months_ahead=state["months_ahead"]
        )
        return {
            "macro_results": macro_result,
            "proj_inf": macro_result["inflation_forecast"]["final_inflation"],
            "proj_repo": macro_result["trajectory"][-1]["projected_repo"],
            "proj_oil": macro_result["trajectory"][-1]["projected_oil"]
        }
    except Exception as e:
        return {"error": f"Macro Agent Error: {str(e)}"}

def run_company_node(state: AgentState):
    """Node 2: Runs Agent 2 to fetch historical company baseline data and full financial statements."""
    if state.get("error"):
        return state
        
    print(f"--> [Node 2] Running Corporate Analysis Agent to fetch baseline for {state['company_name']}...")
    try:
        baseline_data = company_agent.execute(company_name=state["company_name"])
        return {"historical_financials": baseline_data}
    except Exception as e:
        return {"error": f"Corporate Analysis Agent Error: {str(e)}"}

def run_financial_node(state: AgentState):
    """Node 3: Runs the Financial Agent using the state generated by Nodes 1 & 2."""
    if state.get("error"):
        return state # Skip execution if previous node failed
        
    print(f"--> [Node 3] Running Scenario Resilience Agent for {state['company_name']}...")
    try:
        fin_results = financial_agent.execute(
            company_name=state["company_name"],
            historical_data=state.get("historical_financials", {}),
            proj_inf=state["proj_inf"],
            proj_repo=state["proj_repo"],
            proj_brent=state["proj_oil"]
        )
        return {
            "financial_forecasts": fin_results["forecasts"],
            "macro_impacts": fin_results["impact_vs_baseline"]
        }
    except Exception as e:
        return {"error": f"Scenario Resilience Agent Error: {str(e)}"}

def run_report_node(state: AgentState):
    """Node 4: Runs the LLM Agent to write the final report."""
    if state.get("error"):
        return state
        
    print(f"--> [Node 4] Generating Executive Intelligence Report for {state['company_name']}...")
    try:
        # We pass the historical trend, macro context, and future forecasts straight from the state
        history = state.get("historical_financials", {}).get("historical_trend", [])
        
        report = report_agent.execute(
            company_name=state["company_name"],
            historical_data=history,
            macro_data=state.get("macro_results", {}),
            financial_forecasts=state.get("financial_forecasts", {}),
            macro_impacts=state.get("macro_impacts", {})
        )
        return {"investment_report": report}
    except Exception as e:
        return {"error": f"Executive Intelligence Agent Error: {str(e)}"}

# ==========================================================
# 3. Build the LangGraph
# ==========================================================
workflow = StateGraph(AgentState)

# Add our agents as nodes
workflow.add_node("macro_agent", run_macro_node)
workflow.add_node("company_agent", run_company_node)
workflow.add_node("financial_agent", run_financial_node)
workflow.add_node("report_agent", run_report_node)

# Define the flow (Start -> Macro -> Company -> Financial -> Report -> End)
workflow.set_entry_point("macro_agent")
workflow.add_edge("macro_agent", "company_agent")
workflow.add_edge("company_agent", "financial_agent")
workflow.add_edge("financial_agent", "report_agent")
workflow.add_edge("report_agent", END)

# Compile the graph
app_graph = workflow.compile()